### PR TITLE
Update maroto version from 0.42.0 to 1.0.0

### PR DESCRIPTION
**Pull request by johnfercher**
## Overview

Update maroto version to the last v1 stable version.

### CODE REVIEW

**Comment by dwertent** [comment]
Thanks @johnfercher .
Please run `go mod tidy` on the [`kubescape/httphandler`](https://github.com/kubescape/kubescape/tree/master/httphandler) directory as well.

**Comment by johnfercher** [comment]
Done :D

**Comment by johnfercher** [comment]
Failed with this error `Error: Username and password required`. Do I have to do anything to solve this?

**Comment by dwertent** [comment]
> Failed with this error Error: Username and password required. Do I have to do anything to solve this?

This is a known issue with our pipeline :(

Regardless, I see the build passed, so I will merge this. 
Thank you :)

cc: @matthyx

**Review by dwertent — APPROVED** [review]

**Pull request merged**
