### PR TITLE
Option to force enable color output (closes #560)

### LINKED ISSUE #560: Ability to force colored output for CI environments that are not a real TTY
I know that there is the option to specifically disable colors in the output of kubescape, but it would also be nice to be able to force-enable colored output.
This is especially important for CI tools like GitHub Actions, that don't have a real TTY but still have the ability to show ANSI colors correctly.

### PR DESCRIPTION
**Pull request by devmrfitz**
## Describe your changes
Added a flag `--enable-color` to allow 
## Screenshots - If Any (Optional)
image
image

## Issue ticket number and link
#560 
## Checklist before requesting a review
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my code
- [x] If it is a core feature, I have added thorough tests.
- [x] New and existing unit tests pass locally with my changes

**Please open the PR against the `dev` branch (Unless the PR contains only documentation changes)**

### CODE REVIEW

**Review by dwertent — APPROVED** [review]

**Comment by dwertent** [comment]
@devmrfitz Please update logger version to `v0.0.6`

**Comment by devmrfitz** [comment]
@dwertent done

**Comment by dwertent** [comment]
@devmrfitz please merge changes from `kubescape/dev` branch into your dev branch

**Comment by devmrfitz** [comment]
@dwertent done :+1:

**Comment by dwertent** [comment]
#560

**Review by dwertent — APPROVED** [review]

**Pull request merged**
