### PR TITLE
Adding Unit Tests and Bug Fix for core/cautils

### PR DESCRIPTION
**Pull request by mohaidoss**
## PR Type:
Tests

___
## PR Description:
This PR primarily focuses on enhancing the test coverage for the 'core/cautils' module. It introduces unit tests for multiple utility functions and fixes a bug. The key changes are:
- Addition of unit tests for jsonutils, krewutils, workloadmappingutils.
- A bug fix in 'IsKustomizeDirectory' function where it was incorrectly returning the parent directory.
- Addition of tests for 'kustomizedirectory'.
- Refactoring of 'kustomizedirectory.go' to extract the logic of cleaning path directory into a separate function 'cleanPathDir' for better code readability and reusability.

___
## PR Main Files Walkthrough:
<details> <summary>files:</summary>

- `core/cautils/jsonutils_test.go`: Added unit tests for the 'PrettyJson' function in the 'jsonutils' package.
- `core/cautils/krewutils_test.go`: Added unit tests for 'IsKrewPlugin' and 'ExecName' functions in the 'krewutils' package.
- `core/cautils/kustomizedirectory.go`: Refactored the code to extract the logic of cleaning path directory into a separate function 'cleanPathDir'. Fixed a bug in 'IsKustomizeDirectory' function.
- `core/cautils/kustomizedirectory_test.go`: Added unit tests for 'GetKustomizeDirectoryName' and 'cleanPathDir' functions in the 'kustomizedirectory' package.
- `core/cautils/workloadmappingutils_test.go`: Added unit tests for 'MapExternalResource', 'MapHostResources', 'MapImageVulnResources', and 'MapCloudResources' functions in the 'workloadmappingutils' package.
</details>

### CODE REVIEW

**Comment by matthyx** [comment]
is that ready?

**Comment by mohaidoss** [comment]
@matthyx It is ready to merge, but I am following with other tests for cautils (right now `workloadmappingutils.go`), so do you prefer to keep separate PR or ?

**Comment by matthyx** [comment]
It's better if you submit a full test suite for the points, otherwise a small PR is worth 5

**Comment by mohaidoss** [comment]
Identified a bug in `GetKustomizeDirectoryName`, for when the path has no trailing slash it returns the parent directory.

`GetKustomizeDirectoryName("/tmp")` return `"/"` instead of `"/tmp"`

**Comment by coditamar** [comment]
/ask what is the bug that is being fixed? please explain, and even provide an example if possible

**Comment by mohaidoss** [comment]
@coditamar Wow this is impressive ! I'm quite surprised by the explanation + example :exploding_head:

**Review by matthyx — APPROVED** [review]

**Pull request merged**
