### PR TITLE
Adding two helper functions for VAP and CEL admission library

### PR DESCRIPTION
**Pull request by slashben**
## Overview

In this PR I am adding two simple CLI commands related to VAP (Validating Admission Policies) and Kubescape's CEL Admission Policy Library.

One is `kubescape vap-helper deploy-library` that downloads release artifacts from the [CEL Admission Policy Library](https://github.com/kubescape/cel-admission-library) repo (policies) and prints it to the STDOUT (so it can be used in conjunction with `| kubectl apply -f `)

The second is `kubescape vap-helper create-policy-binding --name my-policy-binding --policy C-0012 --namespace test` command that creates a policy binding object YAML and prints it to STDOUT (so it can be used in conjunction with `| kubectl apply -f ` as well)

## Checklist before requesting a review

- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my code
- [x] If it is a core feature, I have added thorough tests.
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by dwertent** [comment]
We should consider naming the command simply `vap` instead of `vap-helper`.
Also, maybe we should use the term `download` instead of `deploy-library`.

A different option, we already have the download command, so maybe we should have the command as follows:
```
kubescape download vap
```

I'm not familiar with the VAP policies to comment on the `create-policy-binding` command.

**Comment by slashben** [comment]
> We should consider naming the command simply vap instead of vap-helper.
I thought about it from the beginning. The reason I choose the "-helper" suffix is that these functionalities are not implementing "VAP" but convenience functions to manage it more easily. 

> Also, maybe we should use the term download instead of deploy-library.
But the core functionality is to deploy the library in the cluster with it, not to download (see my next comment as well)

> A different option, we already have the download command, so maybe we should have the command as follows
We could split the "deploy" to two parts, download and deploy, but I am not sure about the benefits. I don't see the download to be used as a standalone command yet (what for?).

**Comment by matthyx** [comment]
@dwertent LGTM but since I have also committed, can you approve pls?

**Comment by matthyx** [comment]
@dwertent ready to review

**Review by dwertent — APPROVED** [review]

**Pull request merged**
