### PR TITLE
refact(hostsensorutils): refactors host sensor exports

### PR DESCRIPTION
**Pull request by fredbi**
## Overview
This PR is scaffolded on top of #1141  and brings an extra level of refactoring.
The focus of this PR is to unexport private declarations that are not part of the interface exposed by this package.

### CODE REVIEW

**Comment by fredbi** [comment]
cc: @dwertent @matthyx  - follow-up PR, for when the fate of #1141  is decided (I am trying to chunk changes into smaller consistent pieces)

**Comment by matthyx** [comment]
@fredbi ok so this one can be changed into a PR?

**Comment by fredbi** [comment]
@matthyx  yep up to you. You may either review and merge #1141 first, then I rebase this one for merge,
OR you may merge this one: it will embark #1141 and close it automatically.

I've split refactoring actions to relieve a bit the strain of reviewing such PRs.

**Comment by fredbi** [comment]
@matthyx didn't see the dependent PR was merged... :)
Rebased. Ready.

**Review by matthyx — APPROVED** [review]

**Comment by matthyx** [comment]
thanks Fred !

**Pull request merged**
