### PR TITLE
greetings

### PR DESCRIPTION
**Pull request by MrKrishnaAgarwal**
## Describe your changes
I have added a workflow which greets contributors when they open a PR or a Issue
## Screenshots - If Any (Optional)
image

image

## Checklist before requesting a review
- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] New and existing unit tests pass locally with my changes

**Please open the PR against the `dev` branch (Unless the PR contains only documentation changes)**

### CODE REVIEW

**Comment by dwertent** [comment]
Hi, Can you pls add screenshots of the proposed changes

**Comment by MrKrishnaAgarwal** [comment]
> Hi, Can you pls add screenshots of the proposed changes

image

image

**Comment by MrKrishnaAgarwal** [comment]
#675 and #677 
My other pr's
plz review them too

**Review by slashben — APPROVED** [review]

**Comment by slashben** [comment]
@dwertent , will this work?

**Comment by MrKrishnaAgarwal** [comment]
Thanks 👍🏻

**Pull request merged**
