### PR TITLE
Display image scan results

### LINKED ISSUE #430: Proposal: Display images vulnerabilities scan results
Kubescape already supports [pulling the image vulnerabilities scanning results](https://github.com/kubescape/kubescape/blob/master/core/pkg/resourcehandler/k8sresources.go#L67).
We should add the option of displaying these results in a `pretty-print`/`json` format.

If you wish to take this upon yourself, please contact [one of the maintainers](https://github.com/kubescape/kubescape/blob/master/MAINTAINERS.md) for more information

### PR DESCRIPTION
**Pull request by anubhav06**
## Describe your changes
Added the feature of displaying the image scan results, which kubescape downloads from the SaaS, in the requested format.

Running `kubescape scan image -f json --format-version=v2` would display the scan results in JSON format.
Following video showcases the display results:

https://user-images.githubusercontent.com/43821031/200612023-b86bde21-0c76-48e3-b161-74c1cafd2360.mp4

<hr/>

**This is a draft PR:**
If the code design and styling is correct, I can go ahead and implement to display the results in pretty-print format as well

## This PR fixes:

* Resolved #430 

## Checklist before requesting a review

- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by dwertent** [comment]
@anubhav06 Nice, thank you for adding the video demonstrating the `image` command.

My few cents:
1. Since this is technically only downloading the image scan results, I will have this command under the `download` command, meaning it will look as follows: `kubescape download images`
2. There is no need to specify  `--format-version=v2` because there is no `v1` for this
3. In this demonstration you show the json output, is there a pretty printer output? If so, what will it look like?

What are your thoughts?

**Comment by anubhav06** [comment]
Hello @dwertent 

1. Ok. I'll shift the command to work under the `download` command i.e. `kubescape download images`
2. Ok. I'll remove the format-versioning for this command
3. Yes, there will be a pretty-printer output as well. However, I had not implemented it so far as I was waiting for a feedback if my code styling/design for implementing the output in `json` format is correct.
I'll implement the pretty-printer output as well, and then get back to you :)

Thanks

**Comment by anubhav06** [comment]
Update: I have my university exams approaching, so I'll get back on this ASAP

**Comment by anubhav06** [comment]
Hello @dwertent .
[1] Should this download the results from SaaS, after Kubevuln scans the images and submits the image scan results to SaaS
OR
[2] After Kubevuln scans the images, we scan store those results locally and then display them through `download` command.

Which approach should I follow ?

**Comment by dwertent** [comment]
@anubhav06 We should approach the first.
 We are working on storing the Kubevuln in local storage in the cluster, but it is far from ready.

**Comment by anubhav06** [comment]
@dwertent Sorry for another ping, but I'm stuck here:

When KubeScape downloads image scan results from SaaS via an [API call](https://github.com/kubescape/kubescape/blob/master/core/pkg/registryadaptors/armosec/v1/civksadaptor.go#L56), we also pass the `InnerFilters` parameter in the body of the request. The data required for this [`InnerFilters`](https://github.com/kubescape/kubescape/blob/master/core/pkg/registryadaptors/armosec/v1/civksadaptor.go#L52) parameter is accessible when running a complete cluster scan.

How can I then download the image scan results, while running `kubescape download image`, because this way it won't run any cluster scan, and to download the image results via API we need to run cluster scan (for access to `InnerFilter's` value which is the image ID's )

Any help as to how should I go is highly appreciated :)

**Review by PraveenNanda124 — COMMENTED** [review]
Good work

**Comment by anubhav06** [comment]
Hey @dwertent . I've moved the command to `kubescape download images`, for which I'll make a new draft PR soon.

For the pretty print output, I'm thinking of something similar to what we see in the Image Scanning tab of the SaaS:  

image

- Image tag, along with the number of CVE's based on the severity type.

What do you think ?

**Pull request closed without merging**
