### PR TITLE
chore: kubescape bin ignore

### PR DESCRIPTION
**Pull request by testwill**

### CODE REVIEW

**Comment by matthyx** [comment]
Hi @testwill how are you building the httphandler? Normally if you use the `Makefile` you won't have these binaries in your repo.

**Comment by testwill** [comment]
go build

**Comment by matthyx** [comment]
> go build

you should use "make all" because it will clone and compile the `libgit` component which is needed for faster scans of git repos

**Comment by testwill** [comment]
ok

**Pull request closed without merging**
