### PR TITLE
fix(processorhandler): reduce GC pressure

### PR DESCRIPTION
**Pull request by fredbi**
## Overview
This PR reduces GC pressure during scans.

(draft): 
* this draft needs go.mod to be finalized (and also httphandler/go.mod)
* this draft include educational/testing profiling code to be removed

* requires https://github.com/armosec/armoapi-go/pull/44  to be merged and tagged
* requires https://github.com/kubescape/opa-utils/pull/74 to be merged and tagged

Signed-off-by: Frédéric BIDON <fredbi@yahoo.com>

 
## Related issues/PRs:
* #1051 

 cc: @matthyx @dwertent

### CODE REVIEW

**Comment by fredbi** [comment]
@matthyx I believe this one can now be merged.

Or we could be more cautious and wait for https://github.com/kubescape/opa-utils/pull/82 to fix an edge case.
Just let me know where your preference goes.

**Comment by matthyx** [comment]
@fredbi let's bump opa-utils here

**Comment by fredbi** [comment]
> @fredbi let's bump opa-utils here

@matthyx. OK. Please mark that the next tag on opa-utils brings in a breaking change in the reporting model. So we'll have to wait that this is resolved in kubescape (not a big deal from what I could see).

**Comment by fredbi** [comment]
@matthyx @dwertent following update on opa-utils 2c096daf83cc1b351f0620b978680a62a6e9ec0e
The model is no longer compatible, making update to opa-utils@v0.0.299  a breaking change (so much for semver ... :) ).
I am proposing another PR to support this change shortly.

**Comment by dwertent** [comment]
This PR is blocked by #1082 .
Once we merge, we should update here the `opa-utils` package version.

**Comment by fredbi** [comment]
> This PR is blocked by #1082 . Once we merge, we should update here the `opa-utils` package version.

@dwertent yes I had prepared a hasty https://github.com/kubescape/kubescape/pull/1080 , 
but I didn't fully understand all the moving parts. I've closed my patch PR and left @amirmalka quietly complete the integration of the updated models.

**Review by dwertent — APPROVED** [review]

**Pull request merged**
