### PR TITLE
GitRegoStore moved to Regolibrary

### PR DESCRIPTION
**Pull request by kooomix**
## Overview
GitRegoStore packages is moved from opa-utils repo to regolibrary.

- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my code
- [x] If it is a core feature, I have added thorough tests.
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by fredbi** [comment]
@kooomix  last I checked, regolibrary had a cyclic dependency on kubescape, so you could not import it.

**Comment by kooomix** [comment]
> @kooomix last I checked, regolibrary had a cyclic dependency on kubescape, so you could not import it.

Thanks for the feedback, @fredbi, I'll look into it

This might explain why the workflow test failed for windows (though, it did pass on my local ubuntu env as well as ubuntu and mac workflow tests).

**Comment by fredbi** [comment]
@kooomix  I've experimented a bit with your PR to witness the CI failure on windows.
It is indeed difficult to get a trace of what happened. In such a case (identical code, platform-only failure, CI-only failure), I would hypothesize a memory shortage error. A muted failure of the program (no output, nothing else than a non-zero return code) may happen when the program can't allocate memory.
Since kubescape is memory-hungry and go on windows may be less efficient than on other platforms / the windows OS takes more of the VM's memory allocated on CI, this could come as a rational explanation for this failure.
How to verify it? Running on a local Windows successfully would definitely favor CI-only/container limitations issues (going to try that at some point tomorrow). Trying with your github admin to allow large runners (at least for testing) could also help validate this point.

Here are the specs for a standard github runner: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
Here are the specs for larger runners on github paid plans: https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners

As you may see, running windows + kubescape on 7 GB RAM is probably a bit tight.

I have tried yesterday to work around by using the GOGC variable to trigger gc and stop memory from growing earlier, but to no avail.

Hope this helps,

Fred

cc: @dwertent

**Comment by kooomix** [comment]
@fredbi Thanks for the time you took to help on this matter, we have found the issue!
I've used a version that wasn't updated with a windows hot fix @dwertent implemented few weeks ago. After fixing tests has [passed](https://github.com/kubescape/kubescape/pull/1058)!

As for the recent changes you PRed for GitRegoStore - you can choose if you want to do it on RegoLibrary (prefered) or in opa-utils. If the latter, just let me know so I can sync it.

I will completely delete the GitRegoStore in opa-utils after we settled this issue.

Thanks,
Eran

**Review by dwertent — APPROVED** [review]

**Review by dwertent — APPROVED** [review]

**Review by amirmalka — APPROVED** [review]

**Pull request merged**
