### PR TITLE
bug fix for cannot read local artifacts

### LINKED ISSUE #1008: Cannot read local artifacts with useCachedArtifacts=true flag
# Describe the bug
Cannot read the local artifacts files when scanning k8s cluster. In fact kubescape will download all the files from github even if they are already there.

See the code here:

https://github.com/kubescape/kubescape/blob/master/httphandler/handlerequests/v1/datastructuremethods.go#L35

```
if scanRequest.UseCachedArtifacts != nil {
		if useCachedArtifacts := cautils.NewBoolPtr(scanRequest.UseCachedArtifacts); useCachedArtifacts.Get() != nil && !*useCachedArtifacts.Get() {
			scanInfo.UseArtifactsFrom = getter.DefaultLocalStore // Load files from cache (this will prevent kubescape fom downloading the artifacts every time)
		}
}
```

I think the problem maybe in the second if statament:
`!*useCachedArtifacts.Get()` 
which means does not use cached artifacts. If I remove the `!`, I will almost get what I want, but check this out:

https://github.com/kubescape/kubescape/blob/master/core/core/initutils.go#L250

there is no local file loader for attack-tracks, so at last it will trigger a download process.

# Environment
OS: the OS + version you’re running Kubescape on, e.g Ubuntu 22.04 LTS
Version: the version that Kubescape reports when you run `kubescape version`
```
Your current version is:
```

/usr/bin $ ./kubescape version
Your current version is: v2.0.180

# Steps To Reproduce
1. trigger a scan request to kubescape http handler, with `useCachedArtifacts` set to `true`
2. wait for kubescape to scan 

# Expected behavior
A scan without any download process

# Actual Behavior
A scan with full download

# Additional context
I have copy all the artifacts file (but no attack-tracks) into image by modifying Dockerfile.

### PR DESCRIPTION
**Pull request by fdingiit**
## Describe your changes
Code changed for bug 

## This PR fixes:

* Resolved #1008 

## Checklist before requesting a review

- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] New and existing unit tests pass locally with my changes

**Please open the PR against the `dev` branch (Unless the PR contains only documentation changes)**

### CODE REVIEW

**Comment by matthyx** [comment]
@fdingiit thanks for your PR !
Can you rebase with latest `dev`?

**Comment by fdingiit** [comment]
> @fdingiit thanks for your PR ! Can you rebase with latest `dev`?

done

**Comment by matthyx** [comment]
> > @fdingiit thanks for your PR ! Can you rebase with latest `dev`?
> 
> done

sorry, I mean a clean rebase, such as:
```
git fetch upstream
git rebase upstream/dev
```

and then resolve conflicts if any... at the end there should be only one commit if your PR.
Thanks in advance.

**Comment by fdingiit** [comment]
@matthyx done

**Comment by matthyx** [comment]
awesome thanks a lot !
let me run CI and I will review your code with @dwertent on Monday since this is an area I'm not very familiar with, I hope it's fine?

**Comment by fdingiit** [comment]
> 

Don't worry, take your time. 
Have a nice weekend.

**Pull request merged**
