### PR TITLE
correcting the formating of the table in pdf output

### PR DESCRIPTION
**Pull request by nitishchauhan0022**
## Overview

Correcting the formatting of table in pdf output
Resolved: #1108
Update new table looks like this [report.pdf](https://github.com/kubescape/kubescape/files/11575456/report.pdf)

### CODE REVIEW

**Comment by nitishchauhan0022** [comment]
@alegrey91 it is similar but the problem is generateRow is using the getSeverityColumn( ) function which is returing the output with color not supported by pdf package that's why i declared different functino genereateRowPdf which is not using getSeverityColumn  directly. There is one dependency of generateRow which are working with these color codes so that's why i haven't modified generateRow function directly

**Comment by alegrey91** [comment]
Yes, but we can use `generateRow` with your fix for both:
* `./core/pkg/resultshandling/printer/v2/prettyprinter.go`
* `./core/pkg/resultshandling/printer/v2/pdf.go`

Instead of use `generateRow` for `prettyprinter.go` and `generateRowPdf` for `pdf.go`.
Applying your fix to `generateRow` will be enough :)

**Comment by nitishchauhan0022** [comment]
@alegrey91  ok will make the change,one more thing i haven't seen the output of pretty printer previously but the output of .txt file is also breaking since ANSI colors are not supported by text file should i remove the use of colors from pretty printer as well?
image

**Comment by alegrey91** [comment]
Using the same fixed function for `pdf` and `prettyprint` should solve the issue.

**Comment by nitishchauhan0022** [comment]
yes @alegrey91 it will solve this issue, but one change will occur to the output of the terminal, the severity column there will become uncolorised
image

**Comment by alegrey91** [comment]
Mmm, ok, I got your point now. Thanks for reporting this, I didn't noticed.
So, let's leave the code as in your origin commit.
Can you please add a unit-test for the new function that you introduced?

**Comment by nitishchauhan0022** [comment]
Sure

**Review by dwertent — APPROVED** [review]
Well done :)

**Pull request merged**
