### PR TITLE
Refactored LoadPolicy getter, with unit tests

### PR DESCRIPTION
**Pull request by fredbi**
## Describe your changes

This is a follow-up on #1010 , which called for more unit testing.

This PR introduces unit tests to the LoadPolicy file loading utility in core/cautils/getter, following a non-breaking refactoring of the file handling. En passant, a few missing methods that used to be stubbed/TODO have a been implemented.

refact(getter): refactored loadpolicy
    
    * feat: added support for ListControls and GetFrameworks
    * perf: introduced jsoniter unmarshalling for faster decoding
    * introduced stricted error handling & predefined errors:
      * suppressed edge cases when a flaky value is returned instead of an error
    * added full unit tests of LoadPolicy

## This PR fixes:

* Resolved # (TODO(fredbi): create issue for tracking)

## Checklist before requesting a review

- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my code
- [x] If it is a core feature, I have added thorough tests.
- [x] New and existing unit tests pass locally with my changes

**Please open the PR against the `dev` branch (Unless the PR contains only documentation changes)**

### CODE REVIEW

**Comment by fredbi** [comment]
Note to reviewers:
* introducing thorough testing exposed how many subtle edge cases the previous version had introduced. The proposed version is more inclined to raise errors than to return empty/partially empty results.
* test fixtures have just been copied from downloaded files. Generating a mock from structs would be of course better.

**Comment by fredbi** [comment]
@matthyx you mentioned unit testing earlier today. Here are a few ones. Hope this helps.

**Comment by dwertent** [comment]
#1010 Is merged :)

**Comment by fredbi** [comment]
@dwertent thanks David. Rebasing this one so you may get a clearer view of the proposed changes.

**Comment by fredbi** [comment]
@matthyx @dwertent  this little exercise on adding tests begs a few noticeable points, possibly for the future. I am just sharing here a few thoughts, not saying this is necessarily the right way to go.

1. I've added json files for testing, but this is going to be a pain to maintain when the data model evolves
2. The policy getter is pretty inefficient + possibly flaky, as it needs to unmarshal all files and figure out what's inside

1. I've been experimenting a little on github.com/kubescape/opa-utils, with a mock-generating utility I've been using over the years. The idea is to generate random mock structures to check marshal & unmarshal. This could possibly alleviate the need to store "real" test files.
2. if we had a "Kind" field on the file descriptors, it would be much easier to discriminate them, launching the full unmarshalling only for expected kinds (discriminating json can be achieved faster, e.g. with francoispqt/gojay). Overall, this would result in a faster and safer config files scanning & loading.

**Review by dwertent — APPROVED** [review]
Well done!

**Comment by dwertent** [comment]
> I've been experimenting a little on github.com/kubescape/opa-utils, with a mock-generating utility I've been using over the years. The idea is to generate random mock structures to check marshal & unmarshal. This could possibly alleviate the need to store "real" test files.

Nice, can you please share this? I will like to play with it and contribute if needed

> if we had a "Kind" field on the file descriptors, it would be much easier to discriminate them, launching the full unmarshalling only for expected kinds (discriminating json can be achieved faster, e.g. with francoispqt/gojay). Overall, this would result in a faster and safer config files scanning & loading.

I agree, `kind` and `version` should be added to all of the main data structures.
In general, I think we should build the data structures so that in the future we can convert them to CRDs.

**Comment by fredbi** [comment]
>    I've been experimenting a little on github.com/kubescape/opa-utils, with a mock-generating utility I've been using over the years. The idea is to generate random mock structures to check marshal & unmarshal. This could possibly alleviate the need to store "real" test files.

> Nice, can you please share this? I will like to play with it and contribute if needed

Sure @dwertent I am going to push a draft super-WIP PR to github.com/kubescape/opa-utils so you may see my point and the tools I am using to generate mocks from struct. Stay tuned.

**Comment by fredbi** [comment]
@dwertent  David, re-mocking, you may take a look at this WIP: https://github.com/kubescape/opa-utils/pull/70
Just a quick example, nothing ready to be merged yet there, but you get the idea. Cheers.
This is what I've been using (with some variations) over the past couple of years to mock APIs/db structures etc.
The mocker is a little slow, though.

**Pull request merged**
