### PR TITLE
change reference from anubhav06 to project-copacetic

### PR DESCRIPTION
**Pull request by anubhav06**
## Overview

Since copacetic now supports patching kubescape produced results through [plugins](https://github.com/project-copacetic/copacetic/pull/261):

- This PR changes the reference from `anubhav06/copacetic` back to the original repo `project-copacetic/copacetic`.
- Adds a new `ignore-errors` flag which enables to continue patching, even if we are unable to fix certain packages
- Fixes a bug that the output was being printed twice (because of [this](https://github.com/kubescape/kubescape/compare/restructure-img-cmd...anubhav06:copa-grype?expand=1#diff-fedc4ccc05895799a52943980f4a9f7d0fc8c585ae25de15353a33f948048186L100))

### CODE REVIEW

**Comment by dwertent** [comment]
@anubhav06 Please rebase

**Comment by anubhav06** [comment]
The tests are failing at this step:
```
Run docker/login-action@v[2]
Error: Username and password required
```
username and password is missing? I don't see this fail at any other previous PRs nor were these test/YAML files changed, I don't understand why is it failing then. Is it because maybe of a version change in go.mod?

**Comment by matthyx** [comment]
@anubhav06 needs rebase

**Comment by anubhav06** [comment]
good to go

**Comment by matthyx** [comment]
I'll revisit that

**Review by matthyx — DISMISSED** [review]

**Comment by matthyx** [comment]
@anubhav06 sorry looks like I broke your PR... I will give it another try tomorrow

**Comment by anubhav06** [comment]
Although this fixes the build CI, it will not run the patch command correctly
image

This is because the [current grype version](https://github.com/kubescape/kubescape/blob/master/go.mod#L10) being used is `v0.74.2`. This version of grype has a bug and so it doesn't include the value "grype" under the `descriptor.name` field. Copa uses this value in-order to determine the type of vulnerability scanner.
image

This bug has been fixed in the newer version of grype. I tested the latest version [v0.74.7](https://github.com/anchore/grype/releases/tag/v0.74.7) and the generated report contains the missing value. 

However, upgrading grype to the latest version breaks the image scan logic as certain packages which are being used in kubescape, have been deprecated by Grype.

**Comment by matthyx** [comment]
Ok we'll look at it because we should follow up with their releases

**Comment by matthyx** [comment]
Thanks for your work 👍

**Comment by anubhav06** [comment]
I've added a very simple workaround which fixes the missing "grype" value in the descriptor.name field. Until we update to the latest version of grype (which would involve re-factoring the image scan logic as grype has hidden some packages), till then we can use this:
```go
scanResults.ID.Name = "grype"
```
This fixes the grype issue

**Comment by anubhav06** [comment]
@matthyx updated. sorry for the delay

**Comment by matthyx** [comment]
@anubhav06 sorry to bother you one more time, can you rebase and also bump trivy dep:
https://github.com/kubescape/kubescape/pull/1692

I promise I'll merge your work soon after

**Comment by anubhav06** [comment]
trivy is no longer a direct/indirect dependency

**Review by matthyx — APPROVED** [review]

**Comment by matthyx** [comment]
thanks @anubhav06 !

**Pull request merged**
