### PR TITLE
Cosign for quay.io in Github Action

### PR DESCRIPTION
**Pull request by dipankardas011**
Issue #1424 https://github.com/sigstore/cosign/issues/1424

Signed-off-by: Dipankar Das <dipankardas0115@gmail.com>

## Describe your changes
As it was commented out and seen the latest development
It might be now working

## This PR fixes:

* Resolved #

## Checklist before requesting a review

- [ ] My code follows the style guidelines of this project
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] New and existing unit tests pass locally with my changes

**Please open the PR against the `dev` branch (Unless the PR contains only documentation changes)**

### CODE REVIEW

**Comment by dipankardas011** [comment]
@dwertent as you where the original contributor could you tell whether it's ready for not?

**Comment by dipankardas011** [comment]
Used the cosign in my project 
That's why interested in this 😇
https://github.com/dipankardas011/PDF-Editor/blob/46ec6543200109040da31010a86c969797fe6475/.github/workflows/CI.yaml#L58

**Comment by dwertent** [comment]
@dipankardas011 We had issues with casing since we use quay.io
I saw a few months ago they published an article saying they are supporting quay.io but I did not test it.
Please open a public repo in quay.io that will mimic the Kubescape repo so you can test your proposed PR.

**Comment by dipankardas011** [comment]
Will test ✌️
Just wanted to ask is quay free for students

**Comment by dipankardas011** [comment]
Just wanted to tell it will take time due to university exam hope it's okay

**Comment by dipankardas011** [comment]
Screenshot from 2022-09-26 22-22-02
Screenshot from 2022-09-26 22-22-32


Is it correct!

**Comment by dipankardas011** [comment]
Now we have to check whether github actions works or not

**Review by dwertent — APPROVED** [review]
Well done

**Pull request merged**
