### PR TITLE
added GCR adaptor

### LINKED ISSUE #437: Develop GCP GCR image vulnerability adaptor
Kubescape uses image vulnerability information to give enhanced security information about the cluster.

The code has been designed to support multiple vulnerability information sources, but for now only Kubescape SaaS is supported.

Need to implement GCP GCR adaptor to be able to read information from ECR.

See more about the adaptor design [here](https://github.com/armosec/kubescape/blob/master/docs/proposals/container-image-vulnerability-adaptor.md)

Example of the Kubescape Saas adaptor is [here](https://github.com/armosec/kubescape/blob/master/registryadaptors/armosec/v1/civarmoadaptor.go)

### PR DESCRIPTION
**Pull request by AvineshTripathi**
fixes #437

### CODE REVIEW

**Comment by RayAsh37** [comment]
Hi @AvineshTripathi I believe you are supposed to make a PR against the `dev` branch. If you have based your PR branch against master then you might have to rebase it against `dev` branch too.

**Comment by AvineshTripathi** [comment]
Ops! That is why reading the contributing.md is important, will do it in some time

**Comment by AvineshTripathi** [comment]
Ops! Should I close this @RayAsh37 ?

**Comment by RayAsh37** [comment]
yeah seems like you have based your PR branch off of `master` in case you are interested you can look into the **_git rebase workflow_**. But yeah, opening a new PR would be easier if you don't mind the repeated work. Do what suits you the best.

@AvineshTripathi

**Comment by AvineshTripathi** [comment]
I ll do the needful by EOD

**Comment by AvineshTripathi** [comment]
Closing this PR and creating a new one on dev branch

**Pull request closed without merging**
