### PR TITLE
Error Fixed when downloading on azure cloud vm environment 

### PR DESCRIPTION
**Pull request by pwnb0y**
## Describe your changes
In some windows os install.ps1 through error due to dependency on internet explorer engine.
That error is fixed now 
## Issue ticket number and link
#717  https://github.com/kubescape/kubescape/issues/717
## Checklist before requesting a review
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my code
- [x] If it is a core feature, I have added thorough tests.
- [x] New and existing unit tests pass locally with my changes

**Please open the PR against the `dev` branch (Unless the PR contains only documentation changes)**

### CODE REVIEW

**Comment by dwertent** [comment]
> In some windows os install.ps1 through error due to dependency on internet explorer engine

Can you please elaborate? Did you confirm this does not break the installation on other windows machines?

**Comment by pwnb0y** [comment]
Ya, I am sure it does not break

**Comment by pwnb0y** [comment]
Hey @dwertent I design the code in such a way that if my method does't works on any os then it will switch to previous stuff😐

**Comment by pwnb0y** [comment]
If you want any more to change in script then please let me know.

**Review by PraveenNanda124 — COMMENTED** [review]
Good work

**Review by Moshe-Rappaport-CA — APPROVED** [review]

**Comment by craigbox** [comment]
@dwertent ready to merge?

@HollowMan6 FYI in case you want to look at this

**Review by HollowMan6 — APPROVED** [review]
I have tested that in Windows Sandbox and everything works OK, so I can help confirm this does not break the installation on other windows machines.

image

**Comment by craigbox** [comment]
I think this PR isn't required any more as further versions have added BitsTransfer support?

@pwnb0y are you still around to confirm?

**Review by dwertent — APPROVED** [review]

**Pull request merged**
