### PR TITLE
Fix/smelly loops

### LINKED ISSUE #981: Potential bugs with pointers within loops
# Describe the bug
Iterating over a reference using the range operator, then using the pointer to the iterated variable, oftentimes yields
undesirable results. In some cases, this works, but on many occasions, we pass the pointer of the last iteration.

In order to systematically avoid this kind of code smell, I'd advise pinning the iterated reference before using the pointer.

I could detect occurrences of this issue in the following places:
* core/cautils/getter/loadpolicy.go
* core/pkg/opaprocessor/processorhandler.go
* core/pkg/registryadaptors/armosec/v1/civksadaptor.go
* core/pkg/registryadaptors/gcp/v1/gcpadaptor.go
* core/pkg/registryadaptors/gcp/v1/gcpadaptormock.go
* core/pkg/resultshandling/printer/v2/prometheusutils.go
* core/pkg/resultshandling/printer/v2/sarifprinter.go

NOTE: this came from static code analysis performed by the linter "gosec".
We might want to enable such code analysis in CI later, in order to make it harder for such issues to sneak into the code base.

# Environment
OS: the OS + version you’re running Kubescape on, e.g Ubuntu 22.04 LTS
Version: the version that Kubescape reports when you run `kubescape version`
```
Your current version is:
```

# Steps To Reproduce

# Expected behavior

# Actual Behavior
A clear and concise description of what happened. If applicable, add screenshots to help explain your problem.

# Additional context

### PR DESCRIPTION
**Pull request by fredbi**
## Describe your changes
Pinned the iterated variable in loops consuming a pointer to it.

## This PR fixes:

* Resolved #981 

## Checklist before requesting a review

- [x ] My code follows the style guidelines of this project
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [x] New and existing unit tests pass locally with my changes

**Please open the PR against the `dev` branch (Unless the PR contains only documentation changes)**

### CODE REVIEW

**Comment by matthyx** [comment]
LGTM, also agree on linting during CI

**Comment by matthyx** [comment]
I haven't done any memory profiling, but maybe these pointer fixes could help with heap allocations.
Thanks for working on this!

**Comment by fredbi** [comment]
@matthyx this fix is more about ensuring expected results and making the intent more explicit, since passing pointers from an iterated range is at best, flaky (but may work under very specific circumstances).
I don't think this would have any material effect on performances or allocations.

**Comment by fredbi** [comment]
@matthyx  @dwertent the targeted content of this PR had been separated away from the more general "introduce linting" PR (#984) and the changes are now merged in the dev branch. Closing this PR now. Cheers.

**Comment by fredbi** [comment]
Closing as changes are already merged.

**Pull request closed without merging**
