### PR TITLE
added Azure repo scanning support

### LINKED ISSUE #954: feature: Scan Remote repository - `Azure`
## Introduction

Currently, you can scan a remote repository hosted on `GitHub` as follows:
```
kubescape scan https://github.com/<org>/<repo>
``` 
In the [background](https://github.com/kubescape/kubescape/blob/master/core/pkg/resourcehandler/filesloader.go#L93), kubescape will clone the repository and scan it like scanning a local directory.

## Current behavior
This is true [only for repositories hosted on github](https://hub.armosec.io/docs/repository-scanning#scan-remote-repository).

## Desired behavior
Kubescape should support scanning public/private repositories hosted on `Azure`

e.g.
```
kubescape scan https://<>@dev.azure.com/<>/<>/_git/<>
``` 

### Additional information
Private repositories should be supported as well, the token should be passed using an environment variable

### PR DESCRIPTION
**Pull request by anubhav06**
Signed-off-by: Anubhav Gupta <mail.anubhav06@gmail.com>

## Describe your changes
Added support for scanning remote repositories hosted on Azure

**ABOUT THE CHANGES:**
Updated the version of go-git, as the present version [does not support cloning of Azure DevOps repos](https://github.com/go-git/go-git/issues/64).
The [new version](https://github.com/go-git/go-git/pull/613) of go-git has a temporary solution for cloning of Azure repos, as the Azure support is not fully implemented yet.

**Thus, we have to provide the AZURE_TOKEN when scanning even public repos.**

## This PR fixes:

* Resolved #954 

## Checklist before requesting a review

- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my code
- [x] If it is a core feature, I have added thorough tests.
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by matthyx** [comment]
@anubhav06 I have to check why we have this CI test failing before merging... likely on Monday. Thanks for your patience...

**Comment by dwertent** [comment]
@matthyx following our previous conversation regarding the need of using an `AZURE_TOKEN` for cloning also public repos -  Since it is possible to build KS without `git2lib`, I think we should have fewer dependencies as possible on that library.

**Comment by matthyx** [comment]
@anubhav06 error is:
`"msg":"failed to get policies from github release, loading policies from cache","error":"error getting: attack_tracks.json from: \'[https://github.com/kubescape\\\\regolibrary\\\\releases\\\\latest\\\\download\](https://github.com/kubescape////regolibrary////releases////latest////download/)' ,error: HTTP request failed. URL: \'/kubescape%5Cregolibrary%5Creleases%5Clatest%5Cdownload/attack_tracks\', HTTP-ERROR: \'404 Not Found\',`

It clearly comes from the joining of the URL but I will dig deeper tomorrow...

**Comment by matthyx** [comment]
> @anubhav06 error is: `"msg":"failed to get policies from github release, loading policies from cache","error":"error getting: attack_tracks.json from: \'[https://github.com/kubescape\\\\regolibrary\\\\releases\\\\latest\\\\download\](https://github.com/kubescape////regolibrary////releases////latest////download/)' ,error: HTTP request failed. URL: \'/kubescape%5Cregolibrary%5Creleases%5Clatest%5Cdownload/attack_tracks\', HTTP-ERROR: \'404 Not Found\',`
> 
> It clearly comes from the joining of the URL but I will dig deeper tomorrow...

@anubhav06 the fix is here: https://github.com/kubescape/opa-utils/releases/tag/v0.0.223

**Comment by anubhav06** [comment]
Thank you @matthyx for helping with the error. Updating to the latest version of [kubescape/opa-utils](https://github.com/kubescape/opa-utils/releases/tag/v0.0.223) seemed to solve the issue as now when I locally run the command `kubescape scan control C-0048`, I don't get any error.
Should I push the changes and see if it works ?

**Comment by matthyx** [comment]
> Thank you @matthyx for helping with the error. Updating to the latest version of [kubescape/opa-utils](https://github.com/kubescape/opa-utils/releases/tag/v0.0.223) seemed to solve the issue as now when I locally run the command `kubescape scan control C-0048`, I don't get any error. Should I push the changes and see if CI tests are passing ?

yes pls, they will work, I have tested that, so once you push I'll merge - thanks!

**Review by matthyx — APPROVED** [review]

**Pull request merged**
