### PR TITLE
chore: update docs build.ps1

### LINKED ISSUE #1298: Include build.ps1 in docs
# Description

With https://github.com/kubescape/kubescape/pull/1279 merged, we now have a `build.ps1` which can be used instead of `build.bat` and hence this switch needs to be represented in the docs as well, `build.bat` also needs to be removed.

# Environment
OS: `Ubuntu 22.04 LTS`
Version: `v2.3.7`

# Expected behavior

References to `build.bat` need to be replaced with `build.ps1`

# Actual Behavior

References to `build.ps1` have not been removed

### PR DESCRIPTION
**Pull request by XDRAGON2002**
## Overview

As mentioned in the issue, this PR replaces `build.bat` with `build.ps1`

## Additional Information

This is a continuation PR of https://github.com/kubescape/kubescape/pull/1279 and these doc changes were mentioned there

## Related issues/PRs:

Resolved #1298 

## Checklist before requesting a review

- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my code
- [x] If it is a core feature, I have added thorough tests.
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by XDRAGON2002** [comment]
@craigbox just one clarification, this change also needs to be made [here](https://github.com/kubescape/kubescape/wiki/Building#windows). I'm not too sure if I have access to edit that?

**Review by craigbox — APPROVED** [review]

**Comment by craigbox** [comment]
Wiki updated.

**Comment by craigbox** [comment]
The workflow looks to be hung.  Perhaps .\build.ps1 isn't executable from the cmd environment that the runner uses, and you need to fully specify `powershell build.ps1`?

**Comment by craigbox** [comment]
https://github.com/kubescape/kubescape/actions/runs/5657597700/job/15340613152?pr=1299

**Comment by XDRAGON2002** [comment]
@craigbox I saw that the specific step ran on `cmd` shell, so changed it to `pwsh` instead.

**Comment by XDRAGON2002** [comment]
@craigbox interesting, now for some reason the linker doesn't seem to work?

I've tried a few fixes found on different forums and threads but nothing seems to help out.

Everything seems to work on local, but the linker ends up failing here?

**Comment by craigbox** [comment]
@HollowMan6 may have insight here too

**Review by HollowMan6 — APPROVED** [review]
LGTM!

**Comment by HollowMan6** [comment]
But looks like the CI failed: https://github.com/kubescape/kubescape/actions/runs/5701388815/job/15452131551?pr=1299

**Comment by XDRAGON2002** [comment]
> But looks like the CI failed: https://github.com/kubescape/kubescape/actions/runs/5701388815/job/15452131551?pr=1299

Yes

> @craigbox interesting, now for some reason the linker doesn't seem to work?
I've tried a few fixes found on different forums and threads but nothing seems to help out.
Everything seems to work on local, but the linker ends up failing here?

It's been failing for a while now, and I can't seem to figure out why so as the script works locally but not in the CI. Any suggestions as to where we're going wrong?

Thanks!

**Comment by HollowMan6** [comment]
I'm not quite sure about why it fails, unfortunately, maybe it's something related to cache or go versions? Haven't checked that in detail.

**Comment by XDRAGON2002** [comment]
Hm, maybe, I've tried a bunch of things such as changing version, removing caches etc.

Apparently somehow the linker is not able to find necessary files? At least that's what I've interpreted from the logs so far :)

**Comment by HollowMan6** [comment]
Let's try if this will work: https://github.com/kubescape/kubescape/pull/1299/commits/18518237416e49b06ea7175b0299c6dc724a758f

**Comment by HollowMan6** [comment]
> Let's try if this will work: [ee60490](https://github.com/kubescape/kubescape/commit/ee60490574861c52893c3949bed6c04ea82b3ac0)

This is not working. Now I'm running out of ideas.

**Comment by XDRAGON2002** [comment]
> > Let's try if this will work: [ee60490](https://github.com/kubescape/kubescape/commit/ee60490574861c52893c3949bed6c04ea82b3ac0)
> 
> This is not working. Now I'm running out of ideas.

Even I can't figured out what the possible resolution could be.

**Comment by HollowMan6** [comment]
For now, I think it's because we are using the wrong c/cpp compilers. Let's wait again and see if https://github.com/kubescape/kubescape/pull/1299/commits/73bd3a3eb2ab72d8dd29ce8881f90483e855dd94 or something similar will work.

**Comment by HollowMan6** [comment]
Okay, now I know what's going on, C:\\MSYS64\\mingw64\\bin\\gcc.exe doesn't exist at all in the CI. https://github.com/kubescape/kubescape/actions/runs/5737703830/job/15549983491 So this is related to build.ps1, MSYS64 gcc is not installed when running in CI.

**Comment by XDRAGON2002** [comment]
But how would that be possible?

The pacman statements are there anyways and it works on local as well?

**Review by HollowMan6 — CHANGES_REQUESTED** [review]
We should always install packages. This part is different than the build.bat. I will do that change.

**Comment by HollowMan6** [comment]
> But how would that be possible?
> 
> The pacman statements are there anyways and it works on local as well?

I think it's because in the CI, they already have the MSYS2, but lacking the pacman statement

**Comment by HollowMan6** [comment]
I will commit that change to verify this.

**Review by HollowMan6 — APPROVED** [review]
> I think it's because in the CI, they already have the MSYS2, but lacking the pacman packages

I'm right, CI is successful now! https://github.com/kubescape/kubescape/actions/runs/5738432333/job/15552166402?pr=1299

cc: @craigbox @XDRAGON2002

**Comment by XDRAGON2002** [comment]
@HollowMan6 amazing!

I don't work that often with windows tooling, could you elaborate a bit as to exactly what the problem was and how you were able to fix it and how you got the intuition of the fix?

Thanks!

**Comment by HollowMan6** [comment]
> Could you elaborate a bit as to exactly what the problem was and how you were able to fix it and how you got the intuition of the fix?

Okay!

The root cause: GitHub Actions runner's image has pre-installed MSYS2. https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md#msys2 But they haven't pre-installed those Pacman packages dependencies for compiling C code. So it's not right to skip those Pacman package installations according to whether MSYS2 has been installed. https://github.com/kubescape/kubescape/pull/1299/files#diff-3258bc4162690adead72c70b672093e68c92e86a4628148f0015d61738f21b5aR11-R13 

Of course, I didn't ware of this culprit at first. So I was analysing the logs to learn what was going on. In the failed CI, libgit2 is being compiled using [MSVC](https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md#visual-studio-enterprise-2022):  https://github.com/kubescape/kubescape/actions/runs/5701388815/job/15452131551?pr=1299#step:8:17 While the CGO uses mingw32-gcc (since they also have Mingw-w64 11.2.0 pre-installed in their image environment) to link it https://github.com/kubescape/kubescape/actions/runs/5701388815/job/15452131551?pr=1299#step:13:486 And it even can't link the most basic `fprintf` function, which suggest the c toolchain messed up and shouldn't be the code issue.

Now we know what's going on, I began the debug:

> Let's try if this will work: https://github.com/kubescape/kubescape/commit/ee60490574861c52893c3949bed6c04ea82b3ac0

Then finally I found that path C:\MSYS64\mingw64\bin\gcc.exe doesn't exist at all in the CI, which leads to the final solution.

**Comment by XDRAGON2002** [comment]
> > Could you elaborate a bit as to exactly what the problem was and how you were able to fix it and how you got the intuition of the fix?
> 
> Okay!
> 
> The root cause: GitHub Actions runner's image has pre-installed MSYS2. https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md#msys2 But they haven't pre-installed those Pacman packages dependencies for compiling C code. So it's not right to skip those Pacman package installations according to whether MSYS2 has been installed. https://github.com/kubescape/kubescape/pull/1299/files#diff-3258bc4162690adead72c70b672093e68c92e86a4628148f0015d61738f21b5aR11-R13
> 
> Of course, I didn't ware of this culprit at first. So I was analysing the logs to learn what was going on. In the failed CI, libgit2 is being compiled using [MSVC](https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md#visual-studio-enterprise-2022): https://github.com/kubescape/kubescape/actions/runs/5701388815/job/15452131551?pr=1299#step:8:17 While the CGO uses mingw32-gcc (since they also have Mingw-w64 11.2.0 pre-installed in their image environment) to link it https://github.com/kubescape/kubescape/actions/runs/5701388815/job/15452131551?pr=1299#step:13:486 And it even can't link the most basic `fprintf` function, which suggest the c toolchain messed up and shouldn't be the code issue.
> 
> Now we know what's going on, I began the debug:
> 
> > Let's try if this will work: [ee60490](https://github.com/kubescape/kubescape/commit/ee60490574861c52893c3949bed6c04ea82b3ac0)
> 
> Then finally I found that path C:\MSYS64\mingw64\bin\gcc.exe doesn't exist at all in the CI, which leads to the final solution.

@HollowMan6 You sir, are a complete genius!

Amazing!

Thanks a lot for your help, there was no way I could've done this without you!

**Review by craigbox — APPROVED** [review]

**Comment by craigbox** [comment]
@dwertent ✅

**Pull request merged**
