### PR TITLE
Remove control 0086

### PR DESCRIPTION
**Pull request by yuleib**

### CODE REVIEW

**Comment by yuleib** [comment]
related to PR: https://github.com/kubescape/kubescape/pull/1562

**Review by dwertent — APPROVED** [review]

**Comment by yuleib** [comment]
@dwertent - what is going on with the license issues ? why it is blocking the PR if it marked as passed ?

**Comment by matthyx** [comment]
> @dwertent - what is going on with the license issues ? why it is blocking the PR if it marked as passed ?

ignore pls

**Comment by yuleib** [comment]
@matthyx - the builder tests are skipped because of it 
 00-pr_scanner / binary-build (pull_request) Skipped

**Comment by matthyx** [comment]
> @matthyx - the builder tests are skipped because of it 00-pr_scanner / binary-build (pull_request) Skipped

no, the binary build is skipped because you didn't change any go file

**Comment by matthyx** [comment]
> @matthyx - the builder tests are skipped because of it 00-pr_scanner / binary-build (pull_request) Skipped

ok this CI is a mess, after my vacation I will really put some efforts in replacing that completely with https://github.com/kubescape/synchronizer/pull/10

**Comment by yuleib** [comment]
@matthyx so can i ignore and merge it ?

**Comment by matthyx** [comment]
> @matthyx so can i ignore and merge it ?

yes go

**Pull request merged**
