### PR TITLE
Adding Unit Tests for cmd/shared Package

### PR DESCRIPTION
**Pull request by mohaidoss**
## PR Type:
Tests

___
## PR Description:
This PR introduces unit tests for the `cmd/shared` package. The tests are focused on validating the `ScanInfo` struct, particularly the `FailThresholdSeverity` field. Different scenarios are tested including valid and invalid severity levels.

___
## PR Main Files Walkthrough:
<details> <summary>files:</summary>

- `cmd/shared/image_scan_test.go`: Added a new test file for the `shared` package. The file contains a test function `TestValidateImageScanInfo` which tests the validation of a `ScanInfo` struct with different `FailThresholdSeverity` values.
</details>

### CODE REVIEW

**Comment by mohaidoss** [comment]
> [testing with null or empty ScanInfo objects](suggestion: Consider adding more edge cases to the tests, such as testing with null or empty ScanInfo objects. This will ensure that the function behaves as expected in all possible scenarios. [important])

@matthyx Should the empty ScanInfo be considered ?

**Comment by matthyx** [comment]
> > [testing with null or empty ScanInfo objects](suggestion: Consider adding more edge cases to the tests, such as testing with null or empty ScanInfo objects. This will ensure that the function behaves as expected in all possible scenarios. [important])
> 
> @matthyx Should the empty ScanInfo case be considered ?

is it really hard to put it? just to check for nil pointer behavior... (unless it's painful)

**Comment by mohaidoss** [comment]
@matthyx ready to ship :motor_boat:

**Review by matthyx — APPROVED** [review]

**Pull request merged**
