### PR TITLE
docs: fixed some grammatical mistakes in kubescape/httphandler/README…

### PR DESCRIPTION
**Pull request by KashishLakhara04**
## Describe your changes

I fixed some grammatical mistakes in `kubescape/httphandler/README.md` file

 ✅  Edited `/livez - will respond 200 is server is alive` to 
 `/livez - will respond to 200 if the server is alive `

 ✅  Edited `query id=<string> -> request results of a specific scan ID. If empty will return latest results` to 
`query id=<string> -> request results of a specific scan ID. If empty will return the latest results `

 ✅  Edited `Trigger scan and wait for scan to end ` to
`Trigger scan and wait for the scan to end`

 ✅  Edited `Check the scanning status - is the scanning in progress or done.` to
`Check the scanning status - is the scanning in progress or done? `

## Issue ticket number and link
#736 

## Checklist before requesting a review
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my code
- [x] If it is a core feature, I have added thorough tests.
- [x] New and existing unit tests pass locally with my changes

Please open the PR against the `dev` branch (Unless the PR contains only documentation changes)

### CODE REVIEW

**Review by SamiShaikh6810 — APPROVED** [review]
LGTM - 

This commit can be merged.

**Comment by pwnb0y** [comment]
Hi, @KashishLakhara04 you need to use an inbuilt template to submit a pull request.

**Comment by pwnb0y** [comment]
Hi, @KashishLakhara04  you have to put only x in between checklists
eg: ``` [x] My code follows the style guidelines of this project```

**Comment by KashishLakhara04** [comment]
Updated my PR. Any other changes recommended?

**Comment by pwnb0y** [comment]
👍

**Pull request closed without merging**
