### PR TITLE
Refactoring and Adding Tests for Resource Prioritization

### PR DESCRIPTION
**Pull request by mohaidoss**
## type:
Refactoring, Tests

___
## description:
This PR includes refactoring and tests for the resource prioritization feature. The main changes include:
- Refactoring of the `isSupportedKind` function in `prioritizationhandler.go` to use a predefined list of supported kinds.
- Removal of unused functions from `strutils.go` and their corresponding tests from `strutils_test.go`.
- Addition of new tests in `prioritizationhandler_test.go` for the `NewResourcesPrioritizationHandler` and `copyAttackTrack` functions.

___
## main_files_walkthrough:
<details> <summary>files:</summary>

- `core/cautils/strutils.go`: Removed the `ConvertLabelsToString` and `ConvertStringToLabels` functions, which were not being used.
- `core/cautils/strutils_test.go`: Removed the tests for the `ConvertLabelsToString` and `ConvertStringToLabels` functions, which were removed from `strutils.go`.
- `core/pkg/resourcesprioritization/prioritizationhandler.go`: Refactored the `isSupportedKind` function to use a predefined list of supported kinds. Also, added the `copyAttackTrack` function.
- `core/pkg/resourcesprioritization/prioritizationhandler_test.go`: Added new tests for the `NewResourcesPrioritizationHandler` and `copyAttackTrack` functions.
</details>

### CODE REVIEW

**Comment by mohaidoss** [comment]
I added a fix for one failing test, maps and ordering again lol

**Review by amirmalka — DISMISSED** [review]
These refactored functions (`ConvertLabelsToString` and also `ConvertStringToLabels ` are actually not in use)
I would advise to delete them.

**Review by matthyx — APPROVED** [review]
bonus for fixing the other test

**Pull request merged**
