### PR TITLE
feat: add unicode table

### LINKED ISSUE #1059: Make nicer table output
## Overview

```
+-------------------+
| I look like this. |
+-------------------+
```

## Problem
I would rather use Unicode characters to draw nicer lines.

## Solution
https://github.com/olekukonko/tablewriter/pull/207

### PR DESCRIPTION
**Pull request by XDRAGON2002**
## Overview

Updating the version of our table dependency since this version supports unicode character based tables and making the appropriate additions.

## Additional Information

As discussed with @craigbox out of all the possible alternatives available to us for this, this one is the simplest and most efficient so we decided to go with this approach.

## How to Test

`kubescape list controls`
Or any other kubescape command which renders a tabular output

## Examples/Screenshots

Before:
image

After:
image

## Related issues/PRs:

Resolved #1059 

- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my code
- [x] If it is a core feature, I have added thorough tests.
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by craigbox** [comment]
Lovely!   Questions I have are (a) maintainability - is it OK to pin the version we've taken? (b) fallback to plain text if a terminal doesn't support Unicode (what year is this?) which I assume is handled by the library anyway, and if not it's a bug in the library.

**Comment by XDRAGON2002** [comment]
a) It's perfectly fine to pin this version since from a security standpoint I've gone through the changes that have been made till this commit from their last release, this diff can also be found [here](https://github.com/olekukonko/tablewriter/compare/edd1a71..c7d2a8a).
b) Looking at the library code I don't think it's being managed somewhere explicitly at least but almost all terminals now support utf-8 out of the box because of which I don't think it should be a problem.

**Comment by craigbox** [comment]
@matthyx @dwertent this has my LGTM, over to you

**Comment by dwertent** [comment]
@XDRAGON2002 It looks like tests are failing

**Comment by XDRAGON2002** [comment]
@dwertent I had forgotten to update the `go.mod` for the `httphandler` sub module. I've made the appropriate changes now, the checks should pass now.

Thanks!

**Comment by dwertent** [comment]
@XDRAGON2002 Can you please fix the conflicts?

**Comment by XDRAGON2002** [comment]
@dwertent done!

**Comment by craigbox** [comment]
@dwertent this is ready to go ✅

**Review by dwertent — APPROVED** [review]

**Pull request merged**
