### PR TITLE
EKS Support error: failed to get cloud data

### PR DESCRIPTION
**Pull request by comrumino**
Upgraded aws module dependencies to resolve the error `failed to get cloud data. resourceKind: ClusterDescribe; error: not found, ResolveEndpointV2`. This error is a known issue regarding incompatible service module versions. Refer to https://github.com/aws/aws-sdk-go-v2/issues/2370#issuecomment-1953308268 for more details.

This PR relates to [k8s-interface issue 106](https://github.com/kubescape/k8s-interface/issues/106) and  [k8s-interface PR 105](https://github.com/kubescape/k8s-interface/pull/105).

### CODE REVIEW

**Comment by matthyx** [comment]
@comrumino can you update k8s-interface to `[v0.0.173](https://github.com/kubescape/k8s-interface/releases/tag/v0.0.173)` now that it's been released

**Comment by comrumino** [comment]
@matthyx done.

**Review by matthyx — APPROVED** [review]

**Comment by matthyx** [comment]
thanks @comrumino I'll make a release soon

**Comment by matthyx** [comment]
> thanks @comrumino I'll make a release soon

https://github.com/kubescape/kubescape/releases/tag/v3.0.18

**Pull request merged**
