### PR TITLE
build.py is modified

### PR DESCRIPTION
**Pull request by pwnb0y**
## Describe your changes
typo fixed in build.py
## This PR fixes:

* Resolved #

## Checklist before requesting a review

- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my code
- [x] If it is a core feature, I have added thorough tests.
- [x] New and existing unit tests pass locally with my changes

**Please open the PR against the `dev` branch (Unless the PR contains only documentation changes)**

### CODE REVIEW

**Comment by dwertent** [comment]
Is there a reason to add the `.exe` extension? This will PR break the published artifacts naming (since we ignore the `.exe` extension)

**Comment by pwnb0y** [comment]
so, how it runs on windows without a .exe extension

**Comment by dwertent** [comment]
The `install.sh` script is not running on bash?
In any event, if we wish to solve this matter by changing the released executable name, we must support the new name across the different scripts.

**Comment by pwnb0y** [comment]
Ok, then any suggestion on what I have to do to fix it or just leave it for now?

**Pull request closed without merging**
