### PR TITLE
test(hostsensorutils): added unit tests to the hostsensorutils package

### PR DESCRIPTION
**Pull request by fredbi**
## Overview
This PR adds unit tests to the hostsensorutils package.

Coverage is not perfect (74%), but good enough to cover the delicate business of the workerPool.

A limited mock is provided to emulate a kubernetes client with relatively simple test scenarios.

### CODE REVIEW

**Comment by fredbi** [comment]
cc @matthyx  as discussed. This should provide more solid ground to work again on #1066

**Comment by fredbi** [comment]
@matthyx @dwertent  hit an issue with the latest macos on CI (yet another pain with git2go).

**Comment by matthyx** [comment]
> yet another pain with git2go

;_; we should really find a good solution to read these git logs with a native tool

**Comment by fredbi** [comment]
>   yet another pain with git2go
>
> ;_; we should really find a good solution to read these git logs with a native tool

Yes, a few weeks ago I attempted a deep dive into the go-git code and their so-called Merkel-tree diff. I've made some experiments and measurements but failed to find an easy way. The culprit is really how the tree-diff aggressively unpacks git files.

I've compared it with the libgit2 implementation. It's in C but that doesn't explain the difference in performance.
libgit2 implements this feature in a very different way and caches a lot of things when performing the diff.

My takeaway is that the language is not the culprit, the algorithm is. go-git's approach is so convoluted that it is unlikely to change any time soon. For the moment, this remains a difficult problem to solve. Perhaps on our side, we could change the requirement and indulge in a simplified analysis of the git history. I admit that part is unclear to me.

Here is the comment in their tree-diff code:
````
// Many Bothans died to bring us this information, make sure you
// understand the table before modifying this code.
````

**Comment by matthyx** [comment]
@amirmalka wanted to parse `git log` output since almost everybody has git...
Something like https://pkg.go.dev/github.com/tsuyoshiwada/go-gitlog#readme-how-it-works could work...

**Comment by fredbi** [comment]
@matthyx I've fixed the problematic test (libgit2 noise in CI was reporting warnings only). I guess it is good to go.

I'll make another pass after all the tests are merged to factorize the test tooling, as you suggested.

**Review by matthyx — APPROVED** [review]

**Comment by matthyx** [comment]
@fredbi so I do merge this?

**Comment by fredbi** [comment]
@matthyx I guess so yes. It is perfectible, but good enough for now.

**Comment by matthyx** [comment]
done, thanks @fredbi

**Pull request merged**
