### PR TITLE
Adding Comprehensive Test Suite for yamlhelper Package

### PR DESCRIPTION
**Pull request by sulemaanhamza**
## PR Type:
Tests

___
## PR Description:
This PR introduces a comprehensive test suite for the 'yamlhelper' package in the 'fixhandler' directory. The tests cover various scenarios and edge cases for the functions in the package. Here are the key changes:
- Addition of numerous test functions in the 'yamlhelper_test.go' file.
- Each function tests a specific function in the 'yamlhelper' package.
- The tests cover different scenarios including handling of empty strings, line and column matching, node encoding, content indentation, line removal, and more.

___
## PR Main Files Walkthrough:
<details> <summary>files:</summary>

- `core/pkg/fixhandler/yamlhelper_test.go`: Added a comprehensive set of test functions to validate the behavior of the functions in the 'yamlhelper' package. Each test function corresponds to a function in the 'yamlhelper' package and tests various scenarios and edge cases.
</details>

### CODE REVIEW

**Comment by sulemaanhamza** [comment]
@matthyx Could you please review this PR and let me know if it's worth merging? Or do I need to change something? Thanks

**Comment by matthyx** [comment]
Will have a look at it tomorrow, thanks!

**Comment by matthyx** [comment]
@sulemaanhamza can you add a _sign-off_ line to your commits as described here https://github.com/apps/dco

**Review by matthyx — APPROVED** [review]

**Pull request merged**
