### PR TITLE
Adding Test Suite for Prometheus Printer and Handling Invalid Scores

### PR DESCRIPTION
**Pull request by VaibhavMalik4187**
## PR Type:
Tests

___
## PR Description:
This PR introduces the following changes:
- Adds a comprehensive test suite for the Prometheus Printer.
- Implements handling of invalid scores in the `Score` function of the Prometheus Printer.

___
## PR Main Files Walkthrough:
<details> <summary>files:</summary>

- `core/pkg/resultshandling/printer/v2/prometheus.go`: Added handling for invalid scores in the `Score` function. If the score is greater than 100, it is set to 100. If it is less than 0, it is set to 0.
- `core/pkg/resultshandling/printer/v2/prometheus_test.go`: Introduced a new test suite for the Prometheus Printer. This includes tests for the `NewPrometheusPrinter`, `SetWriter`, and `Score` functions. The `Score` function tests include various scenarios such as scores less than 0, greater than 100, and scores of 0, 50, and 100.
</details>

### CODE REVIEW

**Comment by matthyx** [comment]
@VaibhavMalik4187 don't spend too much time on that... we should drop the Prometheus code pretty soon, once we have our https://github.com/kubescape/prometheus-exporter is ready

**Comment by VaibhavMalik4187** [comment]
> @VaibhavMalik4187 don't spend too much time on that... we should drop the Prometheus code pretty soon, once we have our https://github.com/kubescape/prometheus-exporter is ready

Thanks for the heads up, I'll mark this ready as it is.

**Comment by VaibhavMalik4187** [comment]
I'm closing this PR as I've raised a separate [PR](https://github.com/kubescape/kubescape/pull/1536) to address the invalid scores bug.

**Pull request closed without merging**
