### PR TITLE
change basic auth username to x-token-auth

### PR DESCRIPTION
**Pull request by matthyx**
## Overview

In a call with a customer we saw with @yossi77 that the authentication failed with a private BitBucket repo.
After debugging it seems that BitBucket expects a special username `x-token-auth`.
TODO: in the future allow customers to specify a username ?

### CODE REVIEW

**Comment by dwertent** [comment]
@matthyx Is this the "default" user name? How will this fix the issue?
Also, do you propose we get the username and password from env/config?

**Review by dwertent — APPROVED** [review]

**Comment by dwertent** [comment]
TODO: We should add a systemtest for private bitbucket

**Comment by matthyx** [comment]
This is the username expected by bitbucket, but I think it's something new because we used to work

**Comment by matthyx** [comment]
Can you check with Yossi and eventually make a release for the customer?

**Pull request merged**
