### PR TITLE
Adding Test Suite for core/pkg/score

### PR DESCRIPTION
**Pull request by mohaidoss**
## PR Type:
Tests

___
## PR Description:
This PR introduces a comprehensive test suite for the `core/pkg/score` package. The main changes include:
- Addition of new test cases to validate the functionality of the `NewScoreWrapper` function with various scenarios.
- Tests for the `Calculate` function to ensure it handles different report versions correctly.
- Use of the `assert` package for test assertions.

___
## PR Main Files Walkthrough:
<details> <summary>files:</summary>

- `core/pkg/score/score_test.go`: Introduced multiple test functions including `TestNewScoreWrapper`, `TestNewScoreWrapperWithNilOPASessionObj`, `TestNewScoreWrapperWithNilAllResources`, `TestCalculateReturnsNilErrorWhenReportVersionIsEPostureReportV2`, `TestCalculateReturnsErrorWhenReportVersionIsEPostureReportV1`, and `TestCalculateReturnsErrorWhenReportVersionIsNotSupported`. These tests cover various scenarios for the `NewScoreWrapper` and `Calculate` functions.
</details>

### CODE REVIEW

**Comment by mohaidoss** [comment]
I need help to validate the test `TestCalculateReturnsNilErrorWhenReportVersionIsEPostureReportV2`  
See event's discord channel :pray:

**Comment by matthyx** [comment]
> I need help to validate the test `TestCalculateReturnsNilErrorWhenReportVersionIsEPostureReportV2` with some mock data. Anyone to help me with that ? I tried with the `allResourcesMock.json` but I also need the Posture Report data (both v1 & v2 versions). Thanks :D

Hi @mohaidoss let me see if I can find some help...

**Comment by mohaidoss** [comment]
Hi again @matthyx
Could you tell me what should be expected for the test `TestNewScoreWrapperWithNilOPASessionObj` ? Should this case even be tested ?
Right now, it raises a seg violation and breaks everything else.

**Comment by matthyx** [comment]
> Hi again @matthyx Could you tell me what should be expected for the test `TestNewScoreWrapperWithNilOPASessionObj` ? Should this case even be tested ? Right now, it raises a seg violation and breaks everything else.

I think you can remove that, it is very unlikely we'll encounter this nil in reality

**Comment by mohaidoss** [comment]
@matthyx I removed the test, and also found another way to use MockData to test the score with different PostureReport versions

**Comment by mohaidoss** [comment]
@matthyx bump for review

**Review by matthyx — APPROVED** [review]

**Comment by matthyx** [comment]
thanks!

**Pull request merged**
