### PR TITLE
perf(resourcehandler): collect k8s resources in parallel

### LINKED ISSUE #1047: perf: kubernetes resources scanning in parallel
## Overview
Parallel scanning - part 1: k8s resources

## Problem
When scanning my cluster, even if it's small, it takes quite some time to wait on the k8s resources to scan.

## Solution
We may instead easily run such resource retrieval in parallel.

## Alternatives
Making a fancier spinner :).

## Additional context
* k8s resources are not the only object that could benefit from a similar approach.
* for the moment, all resources are buffered in memory structures - perhaps later we'll have to rework this interface and stream results rather than keeping everything in memory
* again, requires more testing (in particular, using the -race option becomes useful)

### PR DESCRIPTION
**Pull request by fredbi**
Signed-off-by: Frédéric BIDON <fredbi@yahoo.com>

## Related issues/PRs:
* Resolved #1047 

## Checklist before requesting a review

put an [x] in the box to get it checked 

- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests. TODO(fred): add more tests
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by fredbi** [comment]
cc: @matthyx @dwertent @vladklokun  an attempt to speed up the resource collection process

Still todo (hence the "draft" status):
* more unit tests,...
* add CLI flag to tune parallelism (by default could be either be a constant, like 10, or something like 2*cpus)

**Comment by matthyx** [comment]
> * something like 2*cpus)

why not use GOPROC or a multiple of it?

**Comment by fredbi** [comment]
@matthyx 
> why not use GOPROC or a multiple of it?

Yes this is what I had in mind. Just added that

**Comment by fredbi** [comment]
@matthyx if we agree with the overall approach, I may invest a little more time to beef up tests.

**Comment by matthyx** [comment]
See my comments in the issue.

**Pull request closed without merging**
