### PR TITLE
Enhancement of 'update' command and addition of tests for version check

### PR DESCRIPTION
**Pull request by mohaidoss**
## PR Type:
Enhancement

___
## PR Description:
This pull request primarily focuses on enhancing the 'update' command in the 'update.go' file and adding tests for the version check functionality in the 'versioncheck_test.go' file. The main changes include:
- In 'update.go', the 'update' command now checks for the latest version of Kubescape and provides more informative messages to the user based on different scenarios.
- In 'versioncheck.go', the 'CheckLatestVersion' function has been updated to assign the latest version to 'LatestReleaseVersion' and not to a new variable.
- New tests have been added in 'versioncheck_test.go' to test the 'CheckLatestVersion' and 'getLatestVersion' functions.

___
## PR Main Files Walkthrough:
<details> <summary>files:</summary>

- `cmd/update/update.go`: Enhanced the 'update' command to check for the latest version of Kubescape and provide more informative messages to the user based on different scenarios.
- `core/cautils/versioncheck.go`: Updated the 'CheckLatestVersion' function to assign the latest version to 'LatestReleaseVersion' and not to a new variable.
- `core/cautils/versioncheck_test.go`: Added new tests to test the 'CheckLatestVersion' and 'getLatestVersion' functions.
</details>

### CODE REVIEW

**Comment by mohaidoss** [comment]
Closes #1506

**Comment by mohaidoss** [comment]
@matthyx Can I further enhance this command, to consider other cases ?

**Comment by matthyx** [comment]
> @matthyx Can I further enhance this command, to consider other cases ?
> 
> See last commit

looks good to me, are you able to add a test for that?

**Comment by mohaidoss** [comment]
> > @matthyx Can I further enhance this command, to consider other cases ?
> > See last commit
> 
> looks good to me, are you able to add a test for that?

Not specifically the update cmd, I don't see how to test that.
But I can def add tests for CheckLaterVersion, to ensure it's returning an Error

**Comment by matthyx** [comment]
> > > @matthyx Can I further enhance this command, to consider other cases ?
> > > See last commit
> > 
> > 
> > looks good to me, are you able to add a test for that?
> 
> Not specifically the update cmd, I don't see how to test that. But I can def add tests for CheckLaterVersion, to ensure it's returning an Error

good enough for me

**Review by matthyx — APPROVED** [review]

**Pull request merged**
