### PR TITLE
Performance Enhancements and Test Additions in prettyprinter/utils.go

### PR DESCRIPTION
**Pull request by VaibhavMalik4187**
## type:
enhancement, tests

___
## description:
This PR introduces performance enhancements and additional tests in the prettyprinter/utils.go file. The main changes include:
- Performance improvements in the `filterCVEsBySeverities` function by creating a map in advance to eliminate the need for repeated string comparisons.
- Performance improvements in the `getSortPackageScores` function by avoiding unnecessary map lookups.
- Performance improvements in the `getSortedCVEsBySeverity` function by avoiding map lookups, efficient sorting, and optimized output.
- Addition of tests for the `GetColor`, `ImageSeverityToInt`, `PrintInfo`, and `GetColorStatus` functions in the utils_test.go file.

___
## main_files_walkthrough:
<details> <summary>files:</summary>

- `core/pkg/resultshandling/printer/v2/prettyprinter/utils.go`: The file has been updated with performance enhancements in the `filterCVEsBySeverities`, `getSortPackageScores`, and `getSortedCVEsBySeverity` functions. These changes aim to improve the efficiency of the code by avoiding unnecessary operations and optimizing the existing ones.
- `core/pkg/resultshandling/printer/v2/prettyprinter/tableprinter/utils/utils_test.go`: This file has been updated with new tests for the `GetColor`, `ImageSeverityToInt`, `PrintInfo`, and `GetColorStatus` functions. These tests aim to ensure the correct functionality of these functions and improve the overall test coverage of the code.
</details>

### CODE REVIEW

**Comment by matthyx** [comment]
@VaibhavMalik4187 let's play with AI... can you review and comment on the suggestions ;-)

**Comment by VaibhavMalik4187** [comment]
> @VaibhavMalik4187 let's play with AI... can you review and comment on the suggestions ;-)

The AI is performing surprisingly well. It's able to catch up to minute details without cluttering the PR.

**Comment by matthyx** [comment]
> > @VaibhavMalik4187 let's play with AI... can you review and comment on the suggestions ;-)
> 
> The AI is performing surprisingly well. It's able to catch up to minute details without cluttering the PR.

Do you think it's worth implementing some of them?

**Comment by VaibhavMalik4187** [comment]
> > > @VaibhavMalik4187 let's play with AI... can you review and comment on the suggestions ;-)
> > 
> > 
> > The AI is performing surprisingly well. It's able to catch up to minute details without cluttering the PR.
> 
> Do you think it's worth implementing some of them?

Yes, and I'm working on it.

**Comment by VaibhavMalik4187** [comment]
> > > @VaibhavMalik4187 let's play with AI... can you review and comment on the suggestions ;-)
> > 
> > 
> > The AI is performing surprisingly well. It's able to catch up to minute details without cluttering the PR.
> 
> Do you think it's worth implementing some of them?

Done

**Review by matthyx — APPROVED** [review]

**Pull request merged**
