### PR TITLE
Bug Fix and Test Addition for sanitizeYaml and revertSanitizeYaml Functions

### PR DESCRIPTION
**Pull request by mohaidoss**
## PR Type:
Bug fix

___
## PR Description:
This PR addresses a minor bug in the `sanitizeYaml` and `revertSanitizeYaml` functions and adds tests for the `core/pkg/fixhandler` package. The changes include:
- A bug fix in the `sanitizeYaml` and `revertSanitizeYaml` functions to handle cases where the input string length is less than 3.
- Addition of numerous tests for various functions in the `core/pkg/fixhandler` package.

___
## PR Main Files Walkthrough:
<details> <summary>files:</summary>

- `core/pkg/fixhandler/fixhandler.go`: Added condition to handle cases where the input string length is less than 3 in `sanitizeYaml` and `revertSanitizeYaml` functions.
- `core/pkg/fixhandler/fixhandler_test.go`: Added numerous tests for various functions in the `core/pkg/fixhandler` package, including `TestJoinStrings`, `TestGetFileString`, `TestDetermineNewlineSeparator`, `TestSanitizeYaml`, `TestReduceYamlExpressions`, and `TestGetLocalPath`.
</details>

### CODE REVIEW

**Comment by matthyx** [comment]
I have failing tests:
```
--- FAIL: TestReduceYamlExpressions (0.00s)
    --- FAIL: TestReduceYamlExpressions/Duplicate_expressions (0.00s)
        fixhandler_test.go:562: 
            	Error Trace:	/home/mbertschy/github.com/kubescape/kubescape/core/pkg/fixhandler/fixhandler_test.go:562
            	Error:      	Not equal: 
            	            	expected: "select(di==0).spec.containers[0].securityContext.allowPrivilegeEscalation |= false | select(di==0).spec.containers[0].securityContext.capabilities.drop += [\"NET_RAW\"]"
            	            	actual  : "select(di==0).spec.containers[0].securityContext.capabilities.drop += [\"NET_RAW\"] | select(di==0).spec.containers[0].securityContext.allowPrivilegeEscalation |= false"
            	            	
            	            	Diff:
            	            	--- Expected
            	            	+++ Actual
            	            	@@ -1 +1 @@
            	            	-select(di==0).spec.containers[0].securityContext.allowPrivilegeEscalation |= false | select(di==0).spec.containers[0].securityContext.capabilities.drop += ["NET_RAW"]
            	            	+select(di==0).spec.containers[0].securityContext.capabilities.drop += ["NET_RAW"] | select(di==0).spec.containers[0].securityContext.allowPrivilegeEscalation |= false
            	Test:       	TestReduceYamlExpressions/Duplicate_expressions
[{1 } {2 } {3 } {3 } {3 } {6 } {6 } {8 } {8 } {10 }]
FAIL
FAIL	github.com/kubescape/kubescape/v3/core/pkg/fixhandler	0.191s
```

**Comment by mohaidoss** [comment]
@matthyx seems like a sort matter, but I made sure to sort the slice :thinking:

**Comment by mohaidoss** [comment]
@matthyx I would need to sort the keys in `reduceYamlExpressions` func to make sure the tests are deterministic. Are we fine with it ?

**Comment by matthyx** [comment]
> @matthyx I would need to sort the keys in `reduceYamlExpressions` func to make sure the tests are deterministic. Are we fine with it ?

I don't understand the fix you're proposing

**Comment by mohaidoss** [comment]
@matthyx Since `resource.YamlExpressions` is a map, it has no guarantee of order. Thus the test will sometimes fail and sometimes succeed.

I added a sort in the function's definition, just before the string join.

**Comment by matthyx** [comment]
> @matthyx Since `resource.YamlExpressions` is a map, it has no guarantee of order. Thus the test will sometimes fail and sometimes succeed.
> 
> I added a sort in the function's definition, just before the string join.

ok, got you know... it's even an improvement now :)

**Review by matthyx — APPROVED** [review]

**Pull request merged**
