### PR TITLE
added Azure repo scanning support

### LINKED ISSUE #954: feature: Scan Remote repository - `Azure`
## Introduction

Currently, you can scan a remote repository hosted on `GitHub` as follows:
```
kubescape scan https://github.com/<org>/<repo>
``` 
In the [background](https://github.com/kubescape/kubescape/blob/master/core/pkg/resourcehandler/filesloader.go#L93), kubescape will clone the repository and scan it like scanning a local directory.

## Current behavior
This is true [only for repositories hosted on github](https://hub.armosec.io/docs/repository-scanning#scan-remote-repository).

## Desired behavior
Kubescape should support scanning public/private repositories hosted on `Azure`

e.g.
```
kubescape scan https://<>@dev.azure.com/<>/<>/_git/<>
``` 

### Additional information
Private repositories should be supported as well, the token should be passed using an environment variable

### PR DESCRIPTION
**Pull request by anubhav06**
Signed-off-by: Anubhav Gupta <mail.anubhav06@gmail.com>

## Describe your changes
Added support for scanning remote repositories hosted on Azure
This PR is linked with "[added Azure API support #6](https://github.com/kubescape/go-git-url/pull/6)", and that needs to be merged before, in order for this to work.

**ABOUT THE CHANGES:**
Updated the version of `go-git`, as the present version [does not support cloning of Azure DevOps repos](https://github.com/go-git/go-git/issues/64). 
The [new version](https://github.com/go-git/go-git/pull/613) of `go-git` has a temporary solution for cloning of Azure repos, as the Azure support is not fully implemented yet.

**Thus, we have to provide the `AZURE_TOKEN` when scanning even public repos.**

## Screenshots - If Any (Optional)

When `AZURE_TOKEN` is provided:

When `AZURE_TOKEN` is not provided:

## This PR fixes:

* Resolved #954

## Checklist before requesting a review

- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by matthyx** [comment]
@anubhav06 can you also rebase with latest `dev` branch and resolve conflicts before I merge?

**Comment by anubhav06** [comment]
For fixing the merge conflicts, should I pull from the `master` or `dev` branch ?

**Comment by matthyx** [comment]
> For fixing the merge conflicts, should I pull from the `master` or `dev` branch ?

dev

**Comment by anubhav06** [comment]
Yes sure, I'm really sorry for adding multiple commits. Fixing this in a few minutes

**Comment by matthyx** [comment]
> Yes sure, I'm really sorry for adding multiple commits. Fixing this in a few minutes

no worries :)

**Comment by anubhav06** [comment]
Apologies, This is taking some time. I'll create a new PR for this by EOD, if it's ok.

**Comment by matthyx** [comment]
> Apologies, This is taking some time. I'll create a new PR for this by EOD, if it's ok.

You have issues rebasing and solving conflicts? No problem take your time and I'll merge it on Monday.
You can check this doc if that helps: https://docs.github.com/en/get-started/using-git/resolving-merge-conflicts-after-a-git-rebase
Good luck !

**Comment by anubhav06** [comment]
Opened #1012 instead of this

**Pull request closed without merging**
