### PR TITLE
Edge-case Handling and Test Enhancements in yamlhelper

### PR DESCRIPTION
**Pull request by sulemaanhamza**
## PR Type:
Bug fix

___
## PR Description:
This PR focuses on improving the robustness of the `yamlhelper` package by handling edge cases that could lead to index out of range errors or other unexpected behaviors. It also adds several edge-case tests to ensure the correctness of these changes. The main changes include:
- Adding checks to prevent index out of range errors in various functions.
- Modifying some functions to handle edge cases such as negative indices or empty slices.
- Adding new test cases to `yamlhelper_test.go` to verify the correct handling of these edge cases.

___
## PR Main Files Walkthrough:
<details> <summary>files:</summary>

- `core/pkg/fixhandler/yamlhelper.go`: Added checks to prevent index out of range errors in functions like `adjustContentLines`, `adjustFixedListLines`, `enocodeIntoYaml`, `indentContent`, `getNodeLine`, `getFirstNodeInLine`, and `removeLines`. Also, modified the `getFirstNodeInLine` function to return -1 when the given line is not found in the list.
- `core/pkg/fixhandler/yamlhelper_test.go`: Added new test cases to verify the correct handling of edge cases in `adjustContentLines`, `adjustFixedListLines`, `enocodeIntoYaml`, `indentContent`, `getNodeLine`, `isSameNode`, `getFirstNodeInLine`, and `removeLines`. These tests ensure that the changes made in `yamlhelper.go` work as expected.
</details>

### CODE REVIEW

**Comment by matthyx** [comment]
@sulemaanhamza what do you think about AI suggestions?

**Comment by sulemaanhamza** [comment]
> @sulemaanhamza what do you think about AI suggestions?

Quite reasonable suggestions. My test cases are still passing if we proceed with AI suggestions. Should I push a single commit with all suggested changes or use the Github feature to commit suggestions on the fly?

**Comment by sulemaanhamza** [comment]
> > Quite reasonable suggestions. My test cases are still passing if we proceed with AI suggestions. Should I push a single commit with all suggested changes or use the Github feature to commit suggestions on the fly?
> 
> Please do it in one commit

@matthyx Done!!

**Review by matthyx — APPROVED** [review]

**Pull request merged**
