### PR TITLE
Upgrade to gopkg.in/yaml.v3

### PR DESCRIPTION
**Pull request by mrueg**
## Describe your changes
Updates to a newer version of gopkg.in/yaml

## Checklist before requesting a review

- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] New and existing unit tests pass locally with my changes

**Please open the PR against the `dev` branch (Unless the PR contains only documentation changes)**

### CODE REVIEW

**Comment by dwertent** [comment]
Why?

**Comment by mrueg** [comment]
https://github.com/go-yaml/yaml/commits/v2 hasn't received any updates since almost 2 years, so it makes sense to move to the more recent version of it https://github.com/go-yaml/yaml/commits/v3

**Review by dwertent — APPROVED** [review]

**Comment by mrueg** [comment]
@dwertent can you trigger ci again please?

**Comment by amirmalka** [comment]
Hi @mrueg !
We had some problematic tests (the reason for the last failure). Could you please pull changes from `dev` branch before I re-run the PR checks?
Thanks!

**Pull request merged**
