### PR TITLE
Chore/slightly more linting

### LINKED ISSUE #1011: chore: augment linting rules
**Is your feature request related to a problem? Please describe.**</br>
This is a follow-up on #985, with a slightly augmented list of coding standard rules, still super basic.

cc: @dwertent @matthyx 

**Describe the solution you'd like.**</br>
Augment the list of enabled linters, with only obvious and/or tested changes.

**Describe alternatives you've considered.**</br>
 > A clear and concise description of any alternative solutions or features you've considered.

**Additional context.**</br>
 > Add any other context or screenshots about the feature request here.

### PR DESCRIPTION
**Pull request by fredbi**
## Describe your changes
This is a follow-up on #984: this PR augments the list of linters.

Not too much: in order to result in a reviewable PR with limited changes.
Enough to bring a little value: 
* fixed HTTP response body leak (unclosed)
* identified dead code (see below)
* enforced commonly adopted code formatting: gofmt, govet, goimports

Since the impact on core/cautils/getter is larger than expected, I indulged in adding a few unit tests there.
The intent is to check the _current_ behavior. There are probably many edge cases with error handling there that
produce flaky result and I did not change that. I the team finds this is desirable, I may address some of these unrelated issues in a follow-up PR.

Further rounds of code analysis & linting would entail more significant changes that would be best secured by introducing more unit tests. 

cc: @dwertent  @matthyx 

### NOTE: how to deal with dead code?
I see 3 options:
1. delete it, for stable packages
2. comment it (approach in this PR), as the codebase is very much in flux
3. mark it with //nolint:deadcode, for later handling - various nolint comments may be reviewed later as candidates for  (non-urgent) refactoring

## This PR fixes:

* Resolved #1011

## Checklist before requesting a review

- [x] My code follows the style guidelines of this project
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my code
- [x] If it is a core feature, I have added thorough tests.
- [x] New and existing unit tests pass locally with my changes

**Please open the PR against the `dev` branch (Unless the PR contains only documentation changes)**

### CODE REVIEW

**Comment by matthyx** [comment]
awesome, let me know when it's ready to review !

**Comment by fredbi** [comment]
@matthyx since I've changed significantly one function (retrieving framework data from files), I took a little time to see how to add unit tests on that part. That would add more changes, though, since core/cautils/getter holds absolutely no tests. What's is your recommendation? Move fast or move cautious?

**Comment by matthyx** [comment]
> What's is your recommendation? Move fast or move cautious?

no rush... improving test coverage is more important at this point.
Thanks for your help!

**Comment by fredbi** [comment]
@matthyx should be reviewable now

**Comment by matthyx** [comment]
@fredbi thanks for the excellent work here, I agree with all changes, LGTM
I especially like the coverage for the load policy getter.

I would like to check with @dwertent on Monday to see how we merge this one (either keep the flow of commits, or squash). But I really appreciate the steps which make reviewing easier.
Good job 👍

**Comment by fredbi** [comment]
> I especially like the coverage for the load policy-getter.

There is a draft PR (currently scaffolded on top of the current one) that brings full coverage (e.g. > 95%),
this time with more significant changes than mere linting.

I am aware that this is a seemingly unimportant/deprioritized feature, but we have to start somewhere, haven't we? :)

**Review by dwertent — APPROVED** [review]

**Pull request merged**
