### PR TITLE
refactor: update node scanner daemonset tolerations

### PR DESCRIPTION
**Pull request by irLinja**
## Overview
I have updated the tolerations for node scanner Daemonset to make it runnable on all nodes of a cluster, regardless of present taints.

Current values:
- node-role.kubernetes.io/control-plane
- node-role.kubernetes.io/master

New value:
An empty key with the operator `Exists` matches all keys, values, and effects which means this will tolerate everything. 
[Reference](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/)

## Additional Information
Kubernetes nodes may be tainted for different reasons or in some cases, tainted differently than what we expect, for instance, a cluster setup with RKE can have additional taints on its masters which prevents the node scanner to meet desired state.

Example of taints:
``` yaml
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/controlplane
    value: "true"
  - effect: NoExecute
    key: node-role.kubernetes.io/etcd
    value: "true"
```

In this example having an additional taint `node-role.kubernetes.io/etcd` will lead to the error below:
```
◓[error] failed to validate host-sensor pods status. error: host-sensor pods number (10) differ than nodes number (13) after deadline exceeded. Kubescape will take data only from the pods below: map[host-scanner-4j9kl:worker-10 host-scanner-58k4d:worker-8 host-scanner-6znqt:worker-9 host-scanner-b4wdn:worker-1 host-scanner-b62w6:worker-2 host-scanner-bvfjk:worker-4 host-scanner-p7cjj:worker-3 host-scanner-qqzpp:worker-7 host-scanner-tv492:worker-6 host-scanner-z898x:worker-5]
```

## Checklist before requesting a review

- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by dwertent** [comment]
Thank you @irLinja!

@matthyx What do you think?

**Comment by matthyx** [comment]
@irLinja so basically an empty `effect` and `key` will tolerate everything everywhere?
Can't we just drop the `taint` for the same effect?

**Comment by irLinja** [comment]
> an empty `effect` and `key` will tolerate everything everywhere?

Yes, it does. this is a common case for workloads like network controllers which must be running on every node in the cluster.

> Can't we just drop the `taint` for the same effect?

By dropping taint do you mean `tolerations`?
If so, no that means the workload has no tolerations and will avoid tainted nodes altogether.

**Comment by matthyx** [comment]
Alright, thanks for the detailed explanation :)

**Review by matthyx — APPROVED** [review]

**Pull request merged**
