### PR TITLE
Done some changes in index file

### PR DESCRIPTION
**Pull request by Coolsum4**
## Describe your changes
Added DOCTYPE and some links in index.html file

## Screenshots - If Any (Optional)
old look 
Screenshot (65)

New look
Screenshot (63)

## Checklist before requesting a review
- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] New and existing unit tests pass locally with my changes

**Please open the PR against the `dev` branch (Unless the PR contains only documentation changes)**

### CODE REVIEW

**Comment by vladklokun** [comment]
Hi!

I’m afraid we don’t use the website directory right now. Or do we, @dwertent? If we don’t, maybe we should consider deleting it altogether?

**Comment by dwertent** [comment]
@vladklokun , no we dont. 
If we start using it, we should work on a nicer landing page

**Comment by Coolsum4** [comment]
I can you help in building the site

**Comment by dwertent** [comment]
I will close this since we are don't using the site for now.
@Coolsum4 if you wish, please come up with a proposal of how the site should look. We can have discussions based on your offer, but for now, I don't see a reason to make small changes without a clear vision of the site.

**Comment by Coolsum4** [comment]
@dwertent I have a plan why to make this forum where people can discuss and get to know their problems like stack flow and after sustain level when our community will become big we will make or brand our selves for a one-stop solution for DevOps like stack flow I know discord is there but if there is a site where common problem solution is present then it will be very great so it will also help kubescape to grow and have a very great and health community so right now this is my vision for this site if you are interested or you have any other suggestion or idea we can discuss here thanks for replying sir.

**Pull request closed without merging**
