### PR TITLE
Fixed typos

### PR DESCRIPTION
**Pull request by trishitchar**
Fixed typos and update some syntax.

## This PR fixes:

* Resolved #

## Checklist before requesting a review

- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my code
- [x] If it is a core feature, I have added thorough tests.
- [x] New and existing unit tests pass locally with my changes

**Please open the PR against the `dev` branch (Unless the PR contains only documentation changes)**

### CODE REVIEW

**Comment by trishitchar** [comment]
@dwertent
I've fixed some typo and also fixed some syntax.
Can you please check and merge.

**Review by deepuyadav004 — APPROVED** [review]

**Comment by trishitchar** [comment]
@deepuyadav004
Can you merge it??

**Comment by deepuyadav004** [comment]
> @deepuyadav004
> Can you merge it??

No, i am not authorised to do.

**Review by akshitagupta15june — APPROVED** [review]

**Comment by trishitchar** [comment]
@dwertent 
All checks are done.
Merge conflict resolved.

Can you review it, please?

**Comment by akshitagupta15june** [comment]
They will merge it!

**Pull request closed without merging**
