### PR TITLE
fix macos runner name

### PR DESCRIPTION
**Pull request by matanshk**
## This PR fixes:

* Resolved #

## Checklist before requesting a review

- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my code
- [x] If it is a core feature, I have added thorough tests.
- [x] New and existing unit tests pass locally with my changes

**Please open the PR against the `dev` branch (Unless the PR contains only documentation changes)**

### CODE REVIEW

**Review by dwertent — CHANGES_REQUESTED** [review]
You will need to fix the `install.sh` file as well

**Comment by matanshk** [comment]
We are not specifying "macos-latest" in install.sh

**Comment by dwertent** [comment]
Please take a look [here](https://github.com/kubescape/kubescape/blob/master/install.sh#L34)

**Comment by amirmalka** [comment]
I don't know if this PR is still relevant, but it is possible to change the runner (to whatever version we need) and still keep the artifacts as they are named.. it only require to update the workflow yamls accordingly (so it will not use `matrix.os`

**Pull request closed without merging**
