### PR TITLE
Clicking on Install links error

### PR DESCRIPTION
**Pull request by om2137**
In README file, if we click on "install windows, install mac or Install on NixOS or Linux/macOS via nix" we don't go to the required section,
instead, we go to the top of the page.

### CODE REVIEW

**Comment by dwertent** [comment]
I see you removed to expand/collapse.
I don't think that is the reason the link is broken.

We added the expand/collapse so the page won't be to overwhelming

**Comment by dwertent** [comment]
Same as #625

**Comment by slashben** [comment]
> I see you removed to expand/collapse. I don't think that is the reason the link is broken.
> 
> We added the expand/collapse so the page won't be to overwhelming

I do think that the collapse causes the link not to work. 

See the test I made here: https://github.com/slashben/markdown-tests

You cannot jump to a link which is collapsed

**Comment by om2137** [comment]
> I see you removed to expand/collapse. I don't think that is the reason the link is broken.
> 
> We added the expand/collapse so the page won't be to overwhelming

As the collapsed section can't be linked, it was not working.
Maybe it can be solved like this?

IMG_20220823_165742

**Comment by om2137** [comment]
is this is right approach?

**Comment by dwertent** [comment]
Fixed #637 
My apologies, I did not notice you suggested a fix.

**Pull request closed without merging**
